export const SYMPTOMS = {
  physical: [
    { id: 'cramps', name: 'Kramp', icon: '💢' },
    { id: 'bloating', name: 'Şişkinlik', icon: '🫄' },
    { id: 'breast_tenderness', name: 'Göğüs Hassasiyeti', icon: '💕' },
    { id: 'back_pain', name: 'Sırt Ağrısı', icon: '🦴' },
    { id: 'headache', name: 'Baş Ağrısı', icon: '🤕' },
    { id: 'fatigue', name: 'Yorgunluk', icon: '😴' },
    { id: 'acne', name: 'Sivilce', icon: '😤' },
    { id: 'food_cravings', name: 'Yemek İsteği', icon: '🍫' },
    { id: 'nausea', name: 'Mide Bulantısı', icon: '🤢' },
    { id: 'diarrhea', name: 'İshal', icon: '💩' },
    { id: 'constipation', name: 'Kabızlık', icon: '😣' },
    { id: 'hot_flashes', name: 'Sıcak Basması', icon: '🔥' },
    { id: 'insomnia', name: 'Uykusuzluk', icon: '😵' },
    { id: 'dizziness', name: 'Baş Dönmesi', icon: '💫' },
    { id: 'muscle_aches', name: 'Kas Ağrıları', icon: '💪' },
  ],
  emotional: [
    { id: 'mood_swings', name: 'Ruh Hali Değişiklikleri', icon: '😤' },
    { id: 'irritability', name: 'Sinirlilik', icon: '😠' },
    { id: 'anxiety', name: 'Kaygı', icon: '😰' },
    { id: 'depression', name: 'Depresyon', icon: '😔' },
    { id: 'stress', name: 'Stres', icon: '😰' },
    { id: 'emotional_sensitivity', name: 'Duygusal Hassasiyet', icon: '🥺' },
    { id: 'anger', name: 'Öfke', icon: '😡' },
    { id: 'sadness', name: 'Üzüntü', icon: '😢' },
    { id: 'happiness', name: 'Mutluluk', icon: '😊' },
    { id: 'excitement', name: 'Heyecan', icon: '🤩' },
  ],
  other: [
    { id: 'libido_changes', name: 'Cinsel İstek Değişiklikleri', icon: '💕' },
    { id: 'appetite_changes', name: 'İştah Değişiklikleri', icon: '🍽️' },
    { id: 'water_retention', name: 'Su Tutulumu', icon: '💧' },
    { id: 'sensitivity_to_light', name: 'Işığa Hassasiyet', icon: '☀️' },
    { id: 'sensitivity_to_sound', name: 'Sese Hassasiyet', icon: '🔊' },
    { id: 'brain_fog', name: 'Beyin Sisi', icon: '🧠' },
    { id: 'memory_issues', name: 'Hafıza Sorunları', icon: '🧠' },
    { id: 'concentration_problems', name: 'Konsantrasyon Sorunları', icon: '🎯' },
  ],
};

export const FLOW_LEVELS = [
  { id: 'light', name: 'Hafif', color: '#FFB3D1', icon: '🩸' },
  { id: 'medium', name: 'Orta', color: '#FF6B9D', icon: '🩸' },
  { id: 'heavy', name: 'Yoğun', color: '#E55A8A', icon: '🩸' },
]; 